// --- TOEIC 問題データ (Volume 1) ---

const defaultData = [
    // ==========================================
    // 📂 グループ: Lv.1_頻出動詞 (Verbs)
    // ==========================================
    { type: "word", text: "accept", answer: "受け入れる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "achieve", answer: "達成する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "acquire", answer: "習得する/買収する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "add", answer: "加える", group: "Lv.1_頻出動詞" },
    { type: "word", text: "adjust", answer: "調整する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "admire", answer: "称賛する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "admit", answer: "認める", group: "Lv.1_頻出動詞" },
    { type: "word", text: "adopt", answer: "採用する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "afford", answer: "余裕がある", group: "Lv.1_頻出動詞" },
    { type: "word", text: "agree", answer: "同意する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "allow", answer: "許可する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "announce", answer: "発表する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "apologize", answer: "謝罪する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "appear", answer: "現れる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "apply", answer: "申し込む/適用する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "appoint", answer: "指名する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "appreciate", answer: "感謝する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "approve", answer: "承認する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "arrive", answer: "到着する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "assign", answer: "割り当てる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "assist", answer: "手伝う", group: "Lv.1_頻出動詞" },
    { type: "word", text: "attach", answer: "添付する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "attend", answer: "出席する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "attract", answer: "引きつける", group: "Lv.1_頻出動詞" },
    { type: "word", text: "avoid", answer: "避ける", group: "Lv.1_頻出動詞" },
    { type: "word", text: "become", answer: "〜になる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "begin", answer: "始める", group: "Lv.1_頻出動詞" },
    { type: "word", text: "believe", answer: "信じる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "belong", answer: "所属する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "borrow", answer: "借りる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "bring", answer: "持ってくる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "build", answer: "建てる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "buy", answer: "買う", group: "Lv.1_頻出動詞" },
    { type: "word", text: "calculate", answer: "計算する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "cancel", answer: "取り消す", group: "Lv.1_頻出動詞" },
    { type: "word", text: "carry", answer: "運ぶ", group: "Lv.1_頻出動詞" },
    { type: "word", text: "celebrate", answer: "祝う", group: "Lv.1_頻出動詞" },
    { type: "word", text: "change", answer: "変える", group: "Lv.1_頻出動詞" },
    { type: "word", text: "choose", answer: "選ぶ", group: "Lv.1_頻出動詞" },
    { type: "word", text: "claim", answer: "主張する/請求する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "clean", answer: "掃除する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "collect", answer: "集める", group: "Lv.1_頻出動詞" },
    { type: "word", text: "combine", answer: "結合させる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "come", answer: "来る", group: "Lv.1_頻出動詞" },
    { type: "word", text: "communicate", answer: "連絡を取り合う", group: "Lv.1_頻出動詞" },
    { type: "word", text: "compare", answer: "比較する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "complain", answer: "不平を言う", group: "Lv.1_頻出動詞" },
    { type: "word", text: "complete", answer: "完了する", group: "Lv.1_頻出動詞" },
    { type: "word", text: "concern", answer: "心配させる", group: "Lv.1_頻出動詞" },
    { type: "word", text: "confirm", answer: "確認する", group: "Lv.1_頻出動詞" },

    // ==========================================
    // 📂 グループ: Lv.1_ビジネス名詞 (Nouns)
    // ==========================================
    { type: "word", text: "access", answer: "アクセス/接近", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "account", answer: "口座/説明", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "advantage", answer: "利点", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "advertisement", answer: "広告", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "advice", answer: "助言", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "agenda", answer: "議題", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "agreement", answer: "合意/契約", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "amount", answer: "量/総計", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "analysis", answer: "分析", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "announcement", answer: "発表", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "application", answer: "申し込み", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "appointment", answer: "予約/約束", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "area", answer: "地域", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "arrangement", answer: "手配/配置", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "arrival", answer: "到着", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "article", answer: "記事", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "attention", answer: "注意", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "audience", answer: "聴衆", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "author", answer: "著者", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "award", answer: "賞", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "balance", answer: "残高/バランス", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "bank", answer: "銀行", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "basis", answer: "基礎/基準", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "bill", answer: "請求書", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "board", answer: "委員会/板", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "branch", answer: "支店", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "brand", answer: "ブランド", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "budget", answer: "予算", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "building", answer: "建物", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "business", answer: "ビジネス/事業", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "campaign", answer: "キャンペーン", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "capacity", answer: "容量/能力", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "career", answer: "経歴", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "case", answer: "場合/事例", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "cash", answer: "現金", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "cause", answer: "原因", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "ceremony", answer: "式典", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "change", answer: "変化/お釣り", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "charge", answer: "料金/責任", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "check", answer: "小切手/確認", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "choice", answer: "選択", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "client", answer: "顧客", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "clothing", answer: "衣類", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "code", answer: "規範/コード", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "colleague", answer: "同僚", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "company", answer: "会社", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "competition", answer: "競争", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "complaint", answer: "苦情", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "conference", answer: "会議", group: "Lv.1_ビジネス名詞" },
    { type: "word", text: "construction", answer: "建設", group: "Lv.1_ビジネス名詞" },

    // ==========================================
    // 📂 グループ: Lv.2_重要形容詞 (Adj)
    // ==========================================
    { type: "word", text: "able", answer: "可能な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "acceptable", answer: "受け入れられる", group: "Lv.2_重要形容詞" },
    { type: "word", text: "accessible", answer: "利用可能な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "accurate", answer: "正確な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "active", answer: "活動的な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "additional", answer: "追加の", group: "Lv.2_重要形容詞" },
    { type: "word", text: "affordable", answer: "手頃な価格の", group: "Lv.2_重要形容詞" },
    { type: "word", text: "annual", answer: "毎年の", group: "Lv.2_重要形容詞" },
    { type: "word", text: "anxious", answer: "心配して", group: "Lv.2_重要形容詞" },
    { type: "word", text: "appropriate", answer: "適切な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "available", answer: "利用できる", group: "Lv.2_重要形容詞" },
    { type: "word", text: "aware", answer: "気付いて", group: "Lv.2_重要形容詞" },
    { type: "word", text: "bad", answer: "悪い", group: "Lv.2_重要形容詞" },
    { type: "word", text: "basic", answer: "基本的な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "beautiful", answer: "美しい", group: "Lv.2_重要形容詞" },
    { type: "word", text: "beneficial", answer: "有益な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "big", answer: "大きい", group: "Lv.2_重要形容詞" },
    { type: "word", text: "brief", answer: "簡潔な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "broad", answer: "広い", group: "Lv.2_重要形容詞" },
    { type: "word", text: "busy", answer: "忙しい", group: "Lv.2_重要形容詞" },
    { type: "word", text: "calm", answer: "穏やかな", group: "Lv.2_重要形容詞" },
    { type: "word", text: "careful", answer: "注意深い", group: "Lv.2_重要形容詞" },
    { type: "word", text: "central", answer: "中心の", group: "Lv.2_重要形容詞" },
    { type: "word", text: "certain", answer: "確かな", group: "Lv.2_重要形容詞" },
    { type: "word", text: "cheap", answer: "安い", group: "Lv.2_重要形容詞" },
    { type: "word", text: "clean", answer: "清潔な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "clear", answer: "明白な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "close", answer: "近い", group: "Lv.2_重要形容詞" },
    { type: "word", text: "comfortable", answer: "快適な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "common", answer: "共通の/普通の", group: "Lv.2_重要形容詞" },
    { type: "word", text: "competitive", answer: "競争力のある", group: "Lv.2_重要形容詞" },
    { type: "word", text: "complete", answer: "完全な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "complex", answer: "複雑な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "comprehensive", answer: "包括的な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "confident", answer: "自信がある", group: "Lv.2_重要形容詞" },
    { type: "word", text: "considerable", answer: "かなりの", group: "Lv.2_重要形容詞" },
    { type: "word", text: "constant", answer: "絶え間ない", group: "Lv.2_重要形容詞" },
    { type: "word", text: "convenient", answer: "便利な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "correct", answer: "正しい", group: "Lv.2_重要形容詞" },
    { type: "word", text: "costly", answer: "高価な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "creative", answer: "創造的な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "critical", answer: "批判的な/重要な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "current", answer: "現在の", group: "Lv.2_重要形容詞" },
    { type: "word", text: "daily", answer: "毎日の", group: "Lv.2_重要形容詞" },
    { type: "word", text: "dangerous", answer: "危険な", group: "Lv.2_重要形容詞" },
    { type: "word", text: "dark", answer: "暗い", group: "Lv.2_重要形容詞" },
    { type: "word", text: "dead", answer: "死んだ", group: "Lv.2_重要形容詞" },
    { type: "word", text: "dear", answer: "親愛なる", group: "Lv.2_重要形容詞" },
    { type: "word", text: "deep", answer: "深い", group: "Lv.2_重要形容詞" },
    { type: "word", text: "defective", answer: "欠陥のある", group: "Lv.2_重要形容詞" },
    { type: "word", text: "definite", answer: "明確な", group: "Lv.2_重要形容詞" },

    // ==========================================
    // 📂 グループ: Part5_Grammar (実践問題)
    // ==========================================
    { 
        type: "part5", 
        text: "Ms. Lee is _____ in applying for the manager position.", 
        answer: "interested", 
        options: ["interest", "interested", "interesting", "interests"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "Please read the instructions _____ before using the machine.", 
        answer: "carefully", 
        options: ["careful", "carefully", "care", "caring"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "The new model is _____ faster than the old one.", 
        answer: "significantly", 
        options: ["significant", "significance", "significantly", "signify"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "We look forward to _____ from you soon.", 
        answer: "hearing", 
        options: ["hear", "heard", "hearing", "hears"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "Despite the rain, the event was _____ well.", 
        answer: "attended", 
        options: ["attend", "attends", "attending", "attended"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "The package should arrive _____ Friday.", 
        answer: "by", 
        options: ["until", "by", "on", "at"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "Employees must _____ their badges at all times.", 
        answer: "wear", 
        options: ["wears", "wearing", "wear", "wore"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "Mr. Tanaka has been working here _____ 10 years.", 
        answer: "for", 
        options: ["since", "during", "for", "while"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "The sales report was _____ by the marketing team.", 
        answer: "prepared", 
        options: ["prepare", "prepares", "preparing", "prepared"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "Please contact us if you need any _____ information.", 
        answer: "further", 
        options: ["far", "further", "farthest", "more far"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "The hotel offers _____ internet access to all guests.", 
        answer: "complimentary", 
        options: ["compliment", "compliments", "complimentary", "complimented"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "He is capable _____ handling difficult customers.", 
        answer: "of", 
        options: ["at", "on", "of", "with"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "The deadline for the project is approaching _____.", 
        answer: "rapidly", 
        options: ["rapid", "rapidness", "rapidly", "rapidity"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "We need to _____ a decision by tomorrow.", 
        answer: "make", 
        options: ["do", "make", "have", "take"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "All visitors are required to _____ at the front desk.", 
        answer: "register", 
        options: ["registers", "registered", "registering", "register"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "The cost of living has risen _____ in recent years.", 
        answer: "dramatically", 
        options: ["dramatic", "dramatically", "dramatics", "drama"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "Mr. Kim is responsible _____ managing the budget.", 
        answer: "for", 
        options: ["to", "of", "with", "for"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "If you have any questions, please _____ free to ask.", 
        answer: "feel", 
        options: ["fall", "fell", "feel", "felt"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "The new software is _____ easier to use than the old one.", 
        answer: "much", 
        options: ["very", "so", "much", "too"], 
        group: "Part5_Grammar" 
    },
    { 
        type: "part5", 
        text: "We specialize _____ custom-made furniture.", 
        answer: "in", 
        options: ["on", "at", "in", "to"], 
        group: "Part5_Grammar" 
    },
    
    // === ショップ限定データ (再掲) ===
    { type: "word", text: "participate", answer: "参加する", group: "Shop_Verbs" },
    { type: "word", text: "reject", answer: "拒否する", group: "Shop_Verbs" },
    { type: "word", text: "approve", answer: "承認する", group: "Shop_Verbs" },
    { type: "word", text: "establish", answer: "設立する", group: "Shop_Verbs" },
    { type: "word", text: "indicate", answer: "指し示す", group: "Shop_Verbs" },

    { type: "part5", text: "The seminar was _____ than I expected.", answer: "more interesting", options: ["interest", "interested", "interesting", "more interesting"], group: "Shop_Part5_Drill" },
    { type: "part5", text: "All employees must _____ the safety regulations.", answer: "follow", options: ["follows", "following", "followed", "follow"], group: "Shop_Part5_Drill" },
];